steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ['build', '-o', 'main', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-service', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/your-service']
images:
  - 'gcr.io/$PROJECT_ID/your-service'
